name: Deploy Preview

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.13.7
  FLUTTER_VERSION: 3.29.2
  PYTHONIOENCODING: utf-8

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2.19.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Prepare dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build app
        shell: bash
        run: flet build web -o dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=test --branch=preview
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}